### ISSUE TITLE
[Bug] color字段未生效

### ISSUE THREAD

**Issue by Go-lu** [17TheWord/QueQiao#11]
### 运行环境

Debian11 OpenJDK 17

### 鹊桥版本号

0.0.4

### 服务端信息

Fabric 1.20.1

### 复现问题的步骤

```markdown
1. 开启服务器
2. apifox正向连接服务端
3. 发送消息
```

### 错误日志

```markdown
无
```

### 截图

**发送端：**
> ![image](https://github.com/user-attachments/assets/9d3d4f69-b03a-475b-8384-c7122008effe) <br>
> ![image](https://github.com/user-attachments/assets/fee1ce42-3577-400b-9eec-c5ad12149334)

----
**游戏内：**
> ![image](https://github.com/user-attachments/assets/a6388897-a281-418c-874c-3dd5fe68a41d)

**Comment by 17TheWord** [comment]
非严重Bug，排期将靠后

**Comment by 17TheWord** [comment]
已在 [Action 12297622270](https://github.com/17TheWord/QueQiao/actions/runs/12297622270) 修复，可以先下载action构建的测试版本
