### ISSUE TITLE
[Enhancement]多服消息互通

### ISSUE THREAD

**Issue by Eternal130** [17TheWord/QueQiao#21]
### 功能建议

现在只能做到服和q群消息互通, 但是如果两个服分别挂了鹊桥, 彼此消息是不互通的, 希望能让与同一个q群互通消息的服务器彼此也能互通消息

**Comment by 17TheWord** [comment]
可以用NoneBot2的minecraft适配器编写插件实现，鹊桥只负责将消息广播到服务器内

**Comment by 17TheWord** [comment]
你的实现端用的是哪个项目？`nonebot-plugin-mcqq` 还是云崽的 `mc-plugin`？如果是 `nonebot-plugin-mcqq`，可以考虑在项目内直接添加这样的功能，如果是云崽的 `mc-plugin`，可以去催更！

**Comment by Eternal130** [comment]
> 你的实现端用的是哪个项目？`nonebot-plugin-mcqq` 还是云崽的 `mc-plugin`？如果是 `nonebot-plugin-mcqq`，可以考虑在项目内直接添加这样的功能，如果是云崽的 `mc-plugin`，可以去催更！

nonebot-plugin-mcqq, 过几天就去加功能

**Comment by 17TheWord** [comment]
临时的方案你可以使用
```python
@temp.handle()
async def _(bot: Bot, event: MessageEvent):
  bots = get_bots()
  msg = event.get_message()
  for temp_bot in bots:
    if bot.self_id != temp_bot.self_id:
      await bot.send_msg(msg)
```

**Comment by Eternal130** [comment]
能互通了, 虽然鹊桥的前缀一直取消不掉,无论如何都剩个[]

**Comment by 17TheWord** [comment]
这个本意是用来做一个自定义前缀的，你可以设置为自己的服务器名或另一个服务器的名字。如果有需求，可以在下个版本也设置为自定义。
