### ISSUE TITLE
[Enhancement]希望能够统一不同服务端的事件名称

### ISSUE THREAD

**Issue by Roberta001** [17TheWord/QueQiao#23]
### 功能建议

以玩家加入事件为例
![image](https://github.com/user-attachments/assets/2cb1e70b-fe48-4e15-bad0-371bcf6ad428)
原版端

![image](https://github.com/user-attachments/assets/3459873f-4184-4aba-9c81-8bca2e642a99)
spigot端

![image](https://github.com/user-attachments/assets/5cdee865-8d8d-40ed-9bfe-aa1e69be4431)
fabric端

![image](https://github.com/user-attachments/assets/93b1bc9c-4083-4704-bc75-98e9d7b1d107)
forge端

四个服务端并不是统一的，希望能够统一事件名称

**Comment by 17TheWord** [comment]
不同服务端对事件的命名不同。即便是一类型服务端，玩家属性也有不同。区别开来也是为了区分服务端，如果你想同时处理多个服务器的事件，可以使用BasePlayerJoinEvent

**Comment by 17TheWord** [comment]
暂无统一事件名的计划，可以使用基础事件进行接收处理
