### ISSUE TITLE
[Enhancement] 希望 QueQiao Spigot 的聊天事件监听优先级改为 MONITOR

### ISSUE THREAD

**Issue by XXY233** [17TheWord/QueQiao#27]
### 功能建议

许多插件会修改聊天消息，比如 CMI 将 `[item]` 转换为手中物品名称的时机为 EventPriority.HIGHEST，现在的插件会将 `[item]` 字符串原样上报，而不是转换后的物品名称。

**Comment by 17TheWord** [comment]
已经在 [`✨ Add monitor priority on player chat event`](https://github.com/17TheWord/QueQiao/commit/b1d3d23b1f45501f7366896a66f36b63ea1ab95c) 仅为spigot聊天添加优先级
可以在 [`action 12214753240`](https://github.com/17TheWord/QueQiao/actions/runs/12214753240) 下载测试使用

**Comment by XXY233** [comment]
非常的不错。谢谢！
